---
Parameters:
  S3BucketName:
    Description: "The name of the S3 bucket that will store the website files"
    Type: String

Resources:
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        # ErrorDocument: error.html 
      CorsConfiguration:
        CorsRules:
          - 
            AllowedMethods: 
              - GET
            AllowedOrigins: 
              - "*"
            AllowedHeaders: 
              - "*"
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  LogsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join 
        - ''
        - - 'logs-'
          - !Ref WebsiteBucket
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  WebsiteBucketBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: PublicAccessPolicy
          Version: 2012-10-17
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref WebsiteBucket
                  - /*
        Bucket: !Ref WebsiteBucket
  
  # SAMPLE for now
  # CloudFrontDistribution:
  #   Type: AWS::CloudFront::Distribution
  #   Properties:
  #     DistributionConfig:
  #       Origins:
  #       - DomainName: heyitschris-com.s3.amazonaws.com
  #         Id: myS3Origin
  #         S3OriginConfig:
  #           OriginAccessIdentity: origin-access-identity/cloudfront/E127EXAMPLE51Z
  #       Enabled: 'true'
  #       Comment: This is a comment
  #       DefaultRootObject: index.html
  #       Logging:
  #         IncludeCookies: 'false'
  #         Bucket: mylogs.s3.amazonaws.com
  #         Prefix: myprefix
  #       Aliases:
  #       - mysite.example.com
  #       - yoursite.example.com
  #       DefaultCacheBehavior:
  #         AllowedMethods:
  #         - DELETE
  #         - GET
  #         - HEAD
  #         - OPTIONS
  #         - PATCH
  #         - POST
  #         - PUT
  #         TargetOriginId: myS3Origin
  #         ForwardedValues:
  #           QueryString: 'false'
  #           Cookies:
  #             Forward: none
  #         TrustedSigners:
  #         - 1234567890EX
  #         - 1234567891EX
  #         ViewerProtocolPolicy: allow-all
  #       PriceClass: PriceClass_200
  #       Restrictions:
  #         GeoRestriction:
  #           RestrictionType: whitelist
  #           Locations:
  #           - AQ
  #           - CV
  #       ViewerCertificate:
  #         CloudFrontDefaultCertificate: 'true'
  #       Tags:
  #         - Key: CostCenter
  #           Value: heyitschris.com

Outputs:
  WebsiteURL:
    Value: !GetAtt 
      - WebsiteBucket
      - WebsiteURL
    Description: URL for website hosted on S3
  S3BucketSecureURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - WebsiteBucket
          - DomainName
    Description: Name of S3 bucket to hold website content