---
Parameters:
  # FIXME set input constraints for these
  S3BucketName:
    Description: "The name of the S3 bucket that will store the website files"
    Type: String
  DynamoDBTableName:
    Description: "The name of the DynamoDB table for the visitor count"
    Type: String

Resources:

  # S3
  ## Static site hosting bucket
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: S3BucketName
      WebsiteConfiguration:
        IndexDocument: index.html
      CorsConfiguration:
        CorsRules:
          - 
            AllowedMethods: 
              - GET
            AllowedOrigins: 
              - "*"
            AllowedHeaders: 
              - "*"
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  # LogsBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: !Join 
  #       - ''
  #       - - 'logs-'
  #         - !Ref WebsiteBucket
  #     Tags:
  #       - Key: CostCenter
  #         Value: heyitschris.com

  ## Bucket policy of the static website hosting bucket
  WebsiteBucketBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        PolicyDocument:
          Id: PublicAccessPolicy
          Version: 2012-10-17
          Statement:
            - Sid: PublicReadForGetBucketObjects
              Effect: Allow
              Principal:
                CanonicalUser: !GetAtt
                  - CloudFrontOAI
                  - S3CanonicalUserId
              Action: 's3:GetObject'
              Resource: !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref WebsiteBucket
                  - /*
        Bucket: !Ref WebsiteBucket
  
  # CloudFront
  ## CloudFront OAI for the bucket policy
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties: 
      CloudFrontOriginAccessIdentityConfig: 
        Comment: !Join 
          - ''
          - - 'The OAI for the bucket: '
            - !Ref WebsiteBucket

  ## Cloudfront distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    # DependsOn:
    #   - HeyitschrisComCertificate
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Join 
            - ''
            - - !Ref WebsiteBucket
              - '.s3.amazonaws.com'
          Id: myS3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Join 
              - ''
              - - 'origin-access-identity/cloudfront/'
                - !Ref CloudFrontOAI
        Enabled: 'true'
        Comment: This is a comment
        DefaultRootObject: index.html
        # Logging:
        #   IncludeCookies: 'false'
        #   Bucket: !Ref LogsBucket
        #   Prefix: CloudFrontLogs
        
        ## AWS support case ID: 7084271721 - parent account
        # Aliases:
        #   - heyitschris.com
        DefaultCacheBehavior:
          AllowedMethods:
          - HEAD
          - GET
          - OPTIONS
          TargetOriginId: myS3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref HeyitschrisComCertificate
          SslSupportMethod: sni-only

  # Visiton Counter Part
  ## DynamoDB Table - FIXME need to manually input item for the first time
  ## FORMAT: id: visitorCount, amount: 0
  DDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: 
        !Ref DynamoDBTableName
      AttributeDefinitions:
        -
          AttributeName: "id"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
  
  ## Lambda role to access visitorCount in DynamoDB
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: dynamodbAccessRole
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
              - dynamodb:*
              Resource: !Join 
                - ''
                - - 'arn:aws:dynamodb:'
                  - !Ref AWS::Region
                  - ':'
                  - !Ref AWS::AccountId
                  - ':table/'
                  - !Ref DDBTable
            - Effect: Allow
              Action:
              - logs:*
              Resource: "*"

  ## Lambda function to retrieve visitorCount from DynamoDB
  VisitorCountLambda:
    Type: AWS::Lambda::Function
    Description: This function retrieves and updates the visitor count in the DynamoDB database.
    Properties:
      Environment:
        Variables:
          databaseName: !Ref DDBTable
      Code:
        ZipFile: |
          import json
          import boto3
          import os

          dynamodb = boto3.resource('dynamodb')
          ddbTableName = os.environ['databaseName']
          table = dynamodb.Table(ddbTableName)

          def handler(event, context):
              response = table.update_item(
                  Key={
                      "id": "visitorCount"
                  },
                  UpdateExpression='SET amount = amount + :inc',
                  ExpressionAttributeValues={
                      ':inc': 1
                  },
                  ReturnValues="UPDATED_NEW"
              )
              print("Response visitor count: ", response["Attributes"]["amount"])
              apiResponse = {
                  "isBase64Encoded": False,
                  "statusCode": 200,
                  "body": json.dumps({
                      "visitorCount": int(float(response["Attributes"]["amount"]))
                  })
              }
              return apiResponse
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.6
      MemorySize: 128
      Timeout: 2
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  # API Gateway
  VisitorCounterAPIGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: VisitorCounterAPI
      Description: The API for the Lambda function that retrieves and updates the current visitor count
      EndpointConfiguration:
        Types:
          - EDGE
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  VisitorCounterAPIGatewayRootMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub
          - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations
          - lambdaArn: !GetAtt VisitorCountLambda.Arn
      ResourceId: !GetAtt VisitorCounterAPIGateway.RootResourceId
      RestApiId: !Ref VisitorCounterAPIGateway

  VisitorCounterAPIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - VisitorCounterAPIGatewayRootMethod
    Properties:
      RestApiId: !Ref VisitorCounterAPIGateway
      StageName: prod # not clean, but it'll do now

  VisitorCounterLambdaApiGatewayInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt VisitorCountLambda.Arn
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${VisitorCounterAPIGateway}/*/GET/

  # This initialization function always fails to create. ignoring and solving it manually for now...
  # InitializeDynamoDB:
  #   Type: Custom::InitFunction
  #   DependsOn: DDBTable
  #   Properties:
  #     ServiceToken: !GetAtt InitFunction.Arn
  #     DynamoTableName: !Ref DDBTable

  # ACM Certificate for heyitschris.com
  HeyitschrisComCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: heyitschris.com
      DomainValidationOptions:
            - DomainName: heyitschris.com
              ValidationDomain: heyitschris.com
      ValidationMethod: EMAIL
      Tags:
        - Key: CostCenter
          Value: heyitschris.com

  
  # Route53
  ## Heyitschris.com Hosted Zone
  HostedZone: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'Heyitschris.com hosted zone migrated from main account'
      Name: heyitschris.com
      HostedZoneTags: 
        - 
          Key: 'CostCenter'
          Value: 'heyitschris.com'

  ## CloudFront Alias DNS record
  DNSRecordCloudFront:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref HostedZone
      Name: api.heyitschris.com
      AliasTarget:
        DNSName: !Sub "https://${VisitorCounterAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
        EvaluateTargetHealth: false
        HostedZoneId: !Ref HostedZone
      TTL: '300'
      Type: A


Outputs:
  CloudFrontURL:
    Value: !Join 
      - ''
      - - 'https://'
        - !GetAtt 
          - CloudFrontDistribution
          - DomainName
    Description: HTTPS Access point
  apiGatewayInvokeURL:
    Value: !Sub "https://${VisitorCounterAPIGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  # These are for debugging purposes
  DEBUGDynamoDBTableRefPsuedoParam:
    Value: !Ref DDBTable
  DEBUGLambdaPolicyResourceARN:
    Value: !Join 
      - ''
      - - 'arn:aws:dynamodb:'
        - !Ref AWS::Region
        - ':'
        - !Ref AWS::AccountId
        - ':table/'
        - !Ref DDBTable