version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "heyitschris-com-infra"
s3_bucket = "heyitschris-com-misc"
s3_prefix = "DeploymentArtifacts"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
