name: Deploy SAM template
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: SAM Build
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "build -t heyitschris-com-infra.yaml"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1

    - name: SAM Deploy
      uses: TractorZoom/sam-cli-action@master
      with:
        sam_command: "deploy -t heyitschris-com-infra.yaml \
          --role-arn arn:aws:iam::130783386804:role/CloudFormationDeployS3StaticWebsiteRole \
          --parameter-overrides ParameterKey=S3BucketName,ParameterValue=heyitschris-com ParameterKey=DynamoDBTableName,ParameterValue=heyitschris.com ParameterKey=WebsiteDomainName,ParameterValue=heyitschris.com \
          --debug"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
